- name: Test Playbook
  hosts: pi
  tasks:
    - name: Print the hostname
      ansible.builtin.command: hostname
      register: hostname_result
      changed_when: false
    - name: Display the hostname
      ansible.builtin.debug:
        msg: "The hostname is {{ hostname_result.stdout }}"
